APT::FTPArchive::Release::Codename "neextra";
APT::FTPArchive::Release::Suite "neextra";
APT::FTPArchive::Release::Version "1";
APT::FTPArchive::Release::Description "The official NeeXtraRepo Repo!";
APT::FTPArchive::Release::Architectures "all";
APT::FTPArchive::Release::Components "xtreleases";
